services:
  app:
    image: taxi-trips
    build:
      context: .
    environment:
      - PARQUET_FILE_PATH=/app/dataset/chicago_taxi_trips_2020.parquet
    volumes:
      - ./dataset:/app/dataset
    network_mode: host
