// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	model "github.com/residwi/chicago-taxi-trips-backend/model"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockITrip is an autogenerated mock type for the ITrip type
type MockITrip struct {
	mock.Mock
}

type MockITrip_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITrip) EXPECT() *MockITrip_Expecter {
	return &MockITrip_Expecter{mock: &_m.Mock}
}

// GetTotalTripsByDateRange provides a mock function with given fields: startDate, endDate
func (_m *MockITrip) GetTotalTripsByDateRange(startDate time.Time, endDate time.Time) ([]model.TotalTrips, error) {
	ret := _m.Called(startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalTripsByDateRange")
	}

	var r0 []model.TotalTrips
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]model.TotalTrips, error)); ok {
		return rf(startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []model.TotalTrips); ok {
		r0 = rf(startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TotalTrips)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITrip_GetTotalTripsByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalTripsByDateRange'
type MockITrip_GetTotalTripsByDateRange_Call struct {
	*mock.Call
}

// GetTotalTripsByDateRange is a helper method to define mock.On call
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockITrip_Expecter) GetTotalTripsByDateRange(startDate interface{}, endDate interface{}) *MockITrip_GetTotalTripsByDateRange_Call {
	return &MockITrip_GetTotalTripsByDateRange_Call{Call: _e.mock.On("GetTotalTripsByDateRange", startDate, endDate)}
}

func (_c *MockITrip_GetTotalTripsByDateRange_Call) Run(run func(startDate time.Time, endDate time.Time)) *MockITrip_GetTotalTripsByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockITrip_GetTotalTripsByDateRange_Call) Return(_a0 []model.TotalTrips, _a1 error) *MockITrip_GetTotalTripsByDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITrip_GetTotalTripsByDateRange_Call) RunAndReturn(run func(time.Time, time.Time) ([]model.TotalTrips, error)) *MockITrip_GetTotalTripsByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITrip creates a new instance of MockITrip. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITrip(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITrip {
	mock := &MockITrip{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
